# Site settings
title: Sid Dixit
name: Sid Dixit

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/siddixit
 - title: LinkedIn
   url: https://www.linkedin.com/in/siddixit

#Any buzzword skills you want to include
skills:
 - Python
 - Java
 - Gosu
 - Microservices
 - Javascript (ES8, React, Angular)
 - API design
 - Spring MVC/Boot
 - Kotlin
 - Gradle
 - JPA
 - SQL/NoSQL
 - REST
 - Technical Architecture
 - Deep learning


#Work experience is required
roles:
 - title: Senior Applications Development Engineer
   start: 2019
   end: Ongoing
   employer: CopperPoint Insurance Companies
   description: Building and managing public consumer facing digital products of CopperPoint on web and mobile that has countrywide daily active users. Website: <a href="https://www.copperpoint.com" taget="_blank">CopperPoint Insurance</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.
 - title: Senior Consultant
   start: 2018
   end: 2019
   employer: CGI Technologies and solutions
   description: Technical Lead for CGI clients for multiple engagements responsible for building solution architecture, developing new ideas, proof of concepts on emerging technologies, leading development activities, managing technical risks, tracking engagement budget, providing technical recommendations and ensuring process compliance.
 - title: Senior Engineer
   start: 2016
   end: 2018
   employer: PricewaterHouseCoppers
   description: Senior Software Engineer within Application and Emerging Technology services, I was provided with a unique opportunity to help our clients identify and prioritize emerging technologies that can help solve their business problems
 - title: Senior Associate
   start: 2009
   end: 2012
   employer: Infosys
   description: Senior Software Engineer for Infosys clients in High Tech manufacturing sector.

#Education is required
education:
 - level: Master of Science (MS)
   date: 2015
   subject: Computer Science
   school: University of Cincinnati
   
 - level: Bachelor of Science (MS)
   date: 2009
   subject: Computer Science
   school: Jaypee University of Information technology.


#List of interesting Github repo/projects to include - optional
github:
 - siddixit/Jquery-Datatables-Custom-Column-VIew

intro: |
  I am a Senior Software Engineer with 10 years experience working in technology. Over the last decade, I have designed and shipped enterprise solutions for fortune 500 companies involving web/server side applications developed from scratch, delivered human centered digital experiences, orchestrated enterprise API's and systems integrations and built seamless automation pipelines. Currently, leading a full-stack team deliver consumer facing digital applications for insurance products.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Cloud platforms</strong>: Certified on Azure and AWS
   <strong>Web Development</strong>: 
   <strong>Development Control</strong>: Project experience in various tools like Jenkins, GIT, JIRA, Swagger .<br/><br/>
 
